services:
  spark:
    version: 4.1.1
    download-source: "https://archive.apache.org/dist/spark/spark-4.1.1/spark-4.1.1-bin-hadoop3.tgz"

provider: ec2

providers:
  ec2:
    key-name: cluster-key
    identity-file: /opt/dataengineering-spark/credentials/keys/cluster-key.pem
    instance-type: t3.micro
    region: us-east-1
    ami: ami-0ed094fb1304fd857
    user: ec2-user
    tenancy: default
    min-root-ebs-size-gb: 8
    instance-initiated-shutdown-behavior: terminate
    authorize-access-from:
      - 0.0.0.0/0

launch:
  num-slaves: 2

debug: true
