services:
  spark:
    version: 3.5.5
    download-source: "s3://dataengineering-releases/spark-3.5.5/"

provider: ec2

providers:
  ec2:
    key-name: cluster-key
    identity-file: credentials/keys/cluster-key.pem
    instance-type: t2.micro
    region: us-east-1
    ami: ami-084a7d336e816906b
    user: ec2-user
    tenancy: default
    min-root-ebs-size-gb: 8
    instance-initiated-shutdown-behavior: terminate
    authorize-access-from:
      - 0.0.0.0/0

launch:
  num-slaves: 2

debug: true
